admin_password: admin
version: latest
ROS_version: 1.5.5
# Empty defaults to latest non-experimental available
k8s_version: ""
server:
  cpus: 1
  memory: 4096
node:
  count: 1
  cpus: 1
  memory: 4096
rke:
  count: 2
  cpus: 1
  memory: 4096
ip:

  server: 172.22.101.100
  node:   172.22.101.110
  rke: 172.22.101.130
linked_clones: true
net:
  private_nic_type: 82545EM
  network_type: private_network
